// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    var checkCommands, prefix, prefix_key;

    prefix = false;
    prefix_key = 65;
    checkCommands = function(keyCode) {};
    return $(function() {
      return $(document).keydown(function(e) {
        console.log('mux');
        console.log('inside keypress');
        console.log(e.keyCode);
        console.log(e);
        console.log('hey');
        console.log(prefix_key);
        console.log(e.keyCode);
        console.log(prefix_letter);
        if (e.keyCode === prefix_key && e.ctrlKey) {
          e.preventDefault();
          console.log('ctrl a!');
          if (!prefix) {
            prefix = true;
            return setTimeout((function() {
              return prefix = false;
            }), 1000);
          } else {
            checkCommands(e.keyCode);
            return prefix = false;
          }
        }
      });
    });
  })();

}).call(this);
